### ISSUE TITLE
Error when running graphsenserest.py

### ISSUE THREAD

**Issue by jjacks95** [graphsense/graphsense-REST#8] opened 2019-05-02 16:43 UTC
Hi,

I have run into an error when trying to run the REST API, everything else has performed correctly, but when I try `python3 graphsenserest.py` I receive this error:

```
Traceback (most recent call last):
  File "graphsenserest.py", line 3, in <module>
    import graphsensedao as gd
  File "/home/user/GraphSense/graphsense-REST/app/graphsensedao.py", line 1, in <module>
    import cassandra.cluster
  File "cassandra/cluster.py", line 63, in init cassandra.cluster
  File "cassandra/metadata.py", line 41, in init cassandra.metadata
  File "cassandra/protocol.py", line 1206, in init cassandra.protocol
  File "cassandra/protocol.py", line 1188, in cassandra.protocol.cython_protocol_handler
TypeError: Class-level classmethod() can only be called on a method_descriptor or instance method.
```

I have cassandra installed and running, and was able to use cassandra.cluster in the blocksci_export.py so not sure as to why there would be an import error.

Any help would be greatly appreciated.

**Comment by defconst** [comment] 2019-05-14 07:47
Duplicate of #7.

**Closed by defconst** 2019-05-14 07:47 UTC
